### ISSUE TITLE
Updating regions on state change

### ISSUE THREAD

**Issue by Bran1304** [mspae/react-wavesurfer#54] opened 2017-07-05 14:20 UTC
Hi there,

I am using the regions plugin and came across a problem with updating the regions on state change.
I have two buttons, one for increasing the start value of the region, the other for decreasing it. However, once I click either of the buttons and thus change the state, the region does not update.

Is there any way this can be done?
Thanks

**Comment by mspae** [comment] 2017-08-10 17:59
Duplicate of #41

**Closed by mspae** 2017-08-10 17:59 UTC
