### ISSUE TITLE
Regions prop not being updated via Regions Plugin Component 

### ISSUE THREAD

**Issue by zschmid** [mspae/react-wavesurfer#58] opened 2017-07-27 03:07 UTC
I've spent hours debugging this without being able to track down exactly what's going on or WHY it's not working the way it should. 

Essentially what the issue comes down to is that it appears that ComponentWillReceiveProps isn't firing within the react-wavesurfer [plugins/regions component](https://github.com/mspae/react-wavesurfer/blob/master/src/plugins/regions.js). 

In my testing I believe it has something to do with the regions component being a child component inside of the Wavesurfer component. 

Here's what my component looks like:
```
<WaveSurfer
  audioFile={this.props.audioFile}
  options={waveOptions}
  playing={this.state.playing}
  pos={this.state.pos}
  onReady={(e)=>this.handleOnReady(e)}
  onPosChange={(e)=>this.handlePosChange(e)}
  onSeek={()=>this.handleSeek()}
  regions={this.state.regions}
>
<Regions
  regions={this.state.regions}
/>
</WaveSurfer>
```

`this.state.regions` is being set dynamically via setState once I receive start and end region information via an API. 
However, this never makes it's way down to the Regions component. I've confirmed by console.logging inside of the ComponentWillReceiveProps method within the react-wavesurfer Regions component. 

If I move the regions component to a top level component (of course this has other side effects and breaks other things) , ComponentWillReceiveProps successfully fires.

Essentially the real issue i'm trying to solve is dynamically loading region information. Because this isn't available when the component initially loads and this issue exists, the region never appears. 

If you have any suggestions, workarounds, or explanations as to why ComponentWillReceiveProps isn't firing within the Regions component, I'd really appreciate it.  I'm stumped...

Let me know what else I can do to help track down the issue. Happy to submit a PR once we track down the root cause. 

Oh and I'm running React 15.6.1

**Comment by mspae** [comment] 2017-08-10 18:05
Duplicate of #41

**Closed** 2017-08-10 18:06 UTC
