### ISSUE TITLE
Use new prop-types package

### ISSUE THREAD

**Issue by rijk** [mspae/react-wavesurfer#51] opened 2017-06-29 17:14 UTC
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

https://facebook.github.io/react/docs/typechecking-with-proptypes.html

Should be an easy fix.

**Comment by mspae** [comment] 2017-08-10 17:58
Duplicate of #39

**Comment by mspae** [comment] 2017-08-13 15:37
Fixed in #61 – thanks @rijk – I'll publish asap

**Closed by mspae** 2017-08-13 15:37 UTC
Labels: deprecation-warning, duplicate
