### ISSUE TITLE
ReferenceError: window is not defined.

### ISSUE THREAD

**Issue by kevinchau321** [mspae/react-wavesurfer#38] opened 2017-05-15 04:10 UTC
Hello, I'm trying to use react-wavesurfer with one of my react components. I'm using webpack, so when I try the import statement:
```
import Wavesurfer from 'react-wavesurfer';
```

I get a server-side error:
```
ReferenceError: window is not defined
```

**Comment by kevinchau321** [comment] 2017-05-15 04:15
This may or may not be an issue with Wavesurfer itself and Babel/Webpack:
https://github.com/katspaugh/wavesurfer.js/issues/767

**Comment by mspae** [comment] 2017-08-10 17:50
Duplicate of https://github.com/mspae/react-wavesurfer/issues/21

**Closed by mspae** 2017-08-10 17:50 UTC
